name: Sky task every day update

on:
  schedule:
    - cron: '10,20,30,40 0 * * *'
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    
    env:
      TZ: Asia/Shanghai
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3


      - name: import py 3.7
        uses: actions/setup-python@v1
        with:
           python-version: 3.7

      - name: install python module
        run: pip3 install -r requirements.txt

      - name: run python script
        run: 
          python3 main.py
